const json=(body,status=200)=>Response.json(body,{status,headers:{'cache-control':'no-store'}});
const text=v=>String(v??'').trim();
const capabilityId=v=>text(v).toUpperCase().replace(/[^A-Z0-9._-]/g,'_');
const capabilityList=v=>[...new Set((Array.isArray(v)?v:[]).map(capabilityId).filter(Boolean))];
const emptyState=()=>({apps:{},versions:{},versionHistory:{}});
async function load(env){if(!env?.OLYMPUS_STATE)throw new Error('OLYMPUS_STATE_NOT_CONFIGURED');const s=(await env.OLYMPUS_STATE.get('olympus-state','json'))||emptyState();s.apps||={};s.versions||={};s.versionHistory||={};for(const app of Object.values(s.apps)){app.capabilityIds=capabilityList(app.capabilityIds);}return s;}
async function save(env,s){await env.OLYMPUS_STATE.put('olympus-state',JSON.stringify(s));}
function registry(s){return Object.values(s.apps).map(a=>{const c=s.versions[a.appId]||null;return{systemId:a.appId,domain:a.destination,currentStatus:c?.status||'UNKNOWN',version:c?.version||null,revision:c?.sourceRevision||null,artifactSha:c?.artifactSha||null,runtime:c?.runtimeIdentity||null,evidence:c?.evidence||[],verifiedAt:c?.updatedAt||null,provenanceRef:c?.provenanceRef||null,owner:c?.owner||a.appId};}).sort((a,b)=>a.systemId.localeCompare(b.systemId));}
function capabilityRegistry(s){const groups=new Map();for(const app of Object.values(s.apps)){for(const id of capabilityList(app.capabilityIds)){const c=s.versions[app.appId]||null;const entry={capabilityId:id,implementationId:app.appId,displayName:app.name||app.appId,destination:app.destination,currentStatus:c?.status||'UNKNOWN',version:c?.version||null,sourceRevision:c?.sourceRevision||null,artifactSha:c?.artifactSha||null,runtimeIdentity:c?.runtimeIdentity||null,verifiedAt:c?.updatedAt||null,provenanceRef:c?.provenanceRef||null};if(!groups.has(id))groups.set(id,[]);groups.get(id).push(entry);}}return[...groups.entries()].map(([id,implementations])=>{implementations.sort((a,b)=>a.implementationId.localeCompare(b.implementationId));const current=implementations.filter(x=>x.currentStatus==='CURRENT');return{capabilityId:id,status:current.length===1?'CURRENT':current.length>1?'CONFLICT':'UNKNOWN',currentImplementation:current.length===1?current[0]:null,implementations,unknowns:current.length>1?['MULTIPLE_CURRENT_IMPLEMENTATIONS']:current.length===0?['CURRENT_IMPLEMENTATION_UNKNOWN']:[]};}).sort((a,b)=>a.capabilityId.localeCompare(b.capabilityId));}
function resolveCapability(s,id){const key=capabilityId(id);return capabilityRegistry(s).find(x=>x.capabilityId===key)||{capabilityId:key||null,status:'UNKNOWN',currentImplementation:null,implementations:[],unknowns:['CAPABILITY_UNKNOWN']};}
function assertNoCapabilityCurrentConflict(s,appId){const app=s.apps[appId];for(const id of capabilityList(app?.capabilityIds)){const conflict=Object.values(s.apps).find(other=>other.appId!==appId&&capabilityList(other.capabilityIds).includes(id)&&s.versions[other.appId]?.status==='CURRENT');if(conflict)throw new Error('CAPABILITY_CURRENT_CONFLICT:'+id+':'+conflict.appId);}}
function directPoint(app){const i=app?.integration;if(i?.mode!=='DIRECT')return null;const p=i?.connectionPoint;if(!p||p.direct!==true||!text(p.target)||!text(p.releaseTruthRef))return null;return p;}
function aionRegistry(s){return registry(s).map(entry=>{const app=s.apps[entry.systemId];const p=directPoint(app);const verified=entry.currentStatus==='CURRENT'&&p;return{...entry,target:verified?p.target:null,releaseTruthRef:verified?p.releaseTruthRef:null};});}
function aionCapabilityResolve(s,id){const resolved=resolveCapability(s,id);if(resolved.status!=='CURRENT'||!resolved.currentImplementation)return{schema:'AION_CAPABILITY_TRUST_PROOF_V1',...resolved,target:null,releaseTruthRef:null};const impl=resolved.currentImplementation;const app=s.apps[impl.implementationId];const p=directPoint(app);if(!p)return{schema:'AION_CAPABILITY_TRUST_PROOF_V1',...resolved,status:'UNKNOWN',target:null,releaseTruthRef:null,unknowns:['CONNECTION_POINT_UNKNOWN']};return{schema:'AION_CAPABILITY_TRUST_PROOF_V1',...resolved,target:p.target,releaseTruthRef:p.releaseTruthRef||impl.provenanceRef||null};}
function aionResolve(s,input={}){const appId=text(input.appId).toLowerCase();const app=s.apps[appId];const current=s.versions[appId]||null;const base={schema:'AION_TRUST_PROOF_V1',appId:appId||null,version:text(input.version)||null,sourceRevision:text(input.sourceRevision)||null,artifactSha:text(input.artifactSha)||null,destination:text(input.destination)||null,target:null,releaseTruthRef:null,verifiedAt:null,status:'UNKNOWN',reason:'TRUTH_UNKNOWN',unknowns:['RELEASE_TRUTH_UNAVAILABLE']};
if(!app)return{...base,reason:'APP_PROFILE_OR_CURRENT_UNKNOWN',unknowns:['APP_PROFILE_OR_CURRENT_UNKNOWN']};
if(!current||current.status!=='CURRENT')return{...base,destination:app.destination||null,reason:'CURRENT_VERSION_UNKNOWN',unknowns:['CURRENT_VERSION_UNKNOWN']};
const p=directPoint(app);if(!p)return{...base,destination:app.destination||null,reason:'CONNECTION_POINT_UNKNOWN',unknowns:['CONNECTION_POINT_UNKNOWN']};
const missing=['version','sourceRevision','artifactSha','destination'].filter(k=>!text(input[k]));if(missing.length)return{...base,destination:app.destination||null,reason:'RESOLUTION_INPUT_UNKNOWN',unknowns:missing.map(k=>k.toUpperCase()+'_UNKNOWN')};
if(text(input.version)!==text(current.version))return{...base,destination:app.destination||null,status:'STALE',reason:'REQUESTED_VERSION_STALE',unknowns:[]};
for(const [key,expected] of [['sourceRevision',current.sourceRevision],['artifactSha',current.artifactSha],['destination',app.destination]])if(text(input[key])!==text(expected))return{...base,destination:app.destination||null,status:'MISMATCH',reason:key.toUpperCase()+'_MISMATCH',unknowns:[]};
return{...base,destination:app.destination||null,target:p.target,releaseTruthRef:p.releaseTruthRef,verifiedAt:new Date().toISOString(),status:'VERIFIED',reason:'OLYMPUS_TRUTH_MATCHED',unknowns:[]};}
export default{async fetch(request,env={}){const u=new URL(request.url);
if(request.method==='GET'&&(u.pathname==='/health'||u.pathname==='/api/health'))return json({ok:true,system:'OLYMPUS',role:'CURRENT_GOVERNANCE_COMMAND_CENTER',runtime:'CLOUDFLARE_WORKER',storage:Boolean(env.OLYMPUS_STATE),aion:true,capabilityRegistry:true});
if(request.method==='GET'&&u.pathname==='/registry/current'){try{const s=await load(env);return json({system:'OLYMPUS',authority:'CURRENT_VERSION_REGISTRY',entries:registry(s)});}catch(e){return json({ok:false,error:e.message},503);}}
if(request.method==='GET'&&u.pathname==='/registry/capabilities'){try{const s=await load(env);return json({system:'OLYMPUS',authority:'CAPABILITY_CURRENT_REGISTRY_V1',entries:capabilityRegistry(s)});}catch(e){return json({ok:false,error:e.message},503);}}
if(request.method==='GET'&&u.pathname==='/aion/registry'){try{const s=await load(env);return json({schema:'AION_TRUST_PROOF_V1',source:'OLYMPUS',entries:aionRegistry(s)});}catch(e){return json({ok:false,error:e.message},503);}}
if(request.method==='GET'&&u.pathname.startsWith('/aion/capabilities/')){try{const id=decodeURIComponent(u.pathname.slice('/aion/capabilities/'.length));return json(aionCapabilityResolve(await load(env),id));}catch(e){return json({ok:false,error:e.message},503);}}
if(request.method==='GET'&&u.pathname.startsWith('/capabilities/')){try{const id=decodeURIComponent(u.pathname.slice('/capabilities/'.length));return json(resolveCapability(await load(env),id));}catch(e){return json({ok:false,error:e.message},503);}}
if(request.method==='POST'&&u.pathname==='/aion/resolve'){try{return json(aionResolve(await load(env),await request.json()));}catch(e){return json({ok:false,error:e.message},503);}}
if(request.method==='POST'&&u.pathname==='/apps'){try{const i=await request.json();const appId=text(i.appId).toLowerCase();if(!appId||!text(i.destination))return json({ok:false,error:'APP_PROFILE_INVALID'},400);const s=await load(env);if(s.apps[appId])return json({ok:false,error:'APP_ALREADY_REGISTERED'},409);s.apps[appId]={appId,name:text(i.name)||appId,destination:text(i.destination),capabilityIds:capabilityList(i.capabilityIds),integration:i.integration||{}};s.versionHistory[appId]||=[];await save(env,s);return json(s.apps[appId],201);}catch(e){return json({ok:false,error:e.message},503);}}
if(request.method==='POST'&&u.pathname==='/reports/current'){try{const i=await request.json();for(const f of['appId','version','sourceRevision','artifactSha','runtimeIdentity','owner','provenanceRef'])if(!text(i[f]))return json({ok:false,error:`CURRENT_REPORT_${f.toUpperCase()}_REQUIRED`},400);const appId=text(i.appId).toLowerCase();const evidence=Array.isArray(i.evidence)?i.evidence.filter(Boolean):[];const status=i.verified===true&&evidence.length?'CURRENT':'PENDING_VERIFICATION';const s=await load(env);s.apps[appId]||={appId,name:text(i.name)||appId,destination:text(i.destination)||appId,capabilityIds:capabilityList(i.capabilityIds),integration:i.integration||{}};if(i.integration)s.apps[appId].integration=i.integration;if(text(i.name))s.apps[appId].name=text(i.name);if(Array.isArray(i.capabilityIds))s.apps[appId].capabilityIds=capabilityList(i.capabilityIds);if(text(i.destination))s.apps[appId].destination=text(i.destination);const c={kind:'VERSION_TRUTH',appId,version:i.version,sourceRevision:i.sourceRevision,artifactSha:i.artifactSha,runtimeIdentity:i.runtimeIdentity,status,evidence,owner:i.owner,provenanceRef:i.provenanceRef,updatedAt:new Date().toISOString()};if(status==='CURRENT'){assertNoCapabilityCurrentConflict(s,appId);const previous=s.versions[appId]||null;s.versions[appId]=c;s.versionHistory[appId]||=[];if(previous&&previous.version!==c.version){const prior=[...s.versionHistory[appId]].reverse().find(x=>x.version===previous.version&&x.sourceRevision===previous.sourceRevision&&x.status!=='SUPERSEDED');if(prior){prior.status='SUPERSEDED';prior.supersededAt=c.updatedAt;}}s.versionHistory[appId].push(c);}await save(env,s);return json(c,status==='CURRENT'?202:200);}catch(e){const conflict=String(e.message||'').startsWith('CAPABILITY_CURRENT_CONFLICT:');return json({ok:false,error:e.message},conflict?409:503);}}
return json({ok:false,error:'NOT_FOUND'},404);}};